require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-erb
plugins:
  - rubocop-factory_bot
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
    - 'config/**/*'
    - 'db/**/*'
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
